# NYC Open Data API Demo
### by Elif Ensari

In [1]:
import pandas as pd
import requests

#Agency_Name
# Borough President of Queens

#https://data.cityofnewyork.us/resource/wewp-mm3p.json

Request the Data

In [2]:
url='https://data.cityofnewyork.us/resource/erm2-nwe9.json'
response = requests.get(url)
data = response.json()

KeyboardInterrupt:

In [20]:
url1= 'https://data.cityofnewyork.us/resource/wewp-mm3p.json'

data1 = requests.get(url1).json()
data1=pd.DataFrame(data1)
len(data1)
data1.head

<bound method NDFrame.head of      unique_id                     date        time                date_time  \
0    159377859  2024-06-10T00:00:00.000  4:05:01 PM  2024-06-10T16:05:01.000
1    159377860  2024-06-10T00:00:00.000  4:56:21 PM  2024-06-10T16:56:21.000
2    159377861  2024-06-10T00:00:00.000  4:56:52 PM  2024-06-10T16:56:52.000
3    159377862  2024-06-10T00:00:00.000  4:57:17 PM  2024-06-10T16:57:17.000
4    159377863  2024-06-10T00:00:00.000  4:48:23 PM  2024-06-10T16:48:23.000
..         ...                      ...         ...                      ...
995  159378867  2024-06-10T00:00:00.000  6:15:10 PM  2024-06-10T18:15:10.000
996  159378868  2024-06-10T00:00:00.000  6:17:31 PM  2024-06-10T18:17:31.000
997  159378869  2024-06-10T00:00:00.000  6:14:43 PM  2024-06-10T18:14:43.000
998  159378870  2024-06-10T00:00:00.000  5:51:55 PM  2024-06-10T17:51:55.000
999  159378871  2024-06-10T00:00:00.000  6:16:28 PM  2024-06-10T18:16:28.000

                        inquiry_name  \
0               Directory Assistance
1     City Agency or Worker Feedback
2            IDNYC Municipal ID Card
3     City Agency or Worker Feedback
4                 Bulk Item Disposal
..                               ...
995  Property Tax Payment Assistance
996                 Blocked Driveway
997     Pothole or Cave-In on Street
998   City Agency or Worker Feedback
999  Apartment Maintenance Complaint

                                     brief_description
0    Get the phone number or address of a specific ...
1    Give a complaint, compliment, or comment on th...
2    Learn about and apply for the New York City's ...
3    Give a complaint, compliment, or comment on th...
4          Learn how to get rid of large, bulky items.
..                                                 ...
995      Get help with a property tax payment problem.
996   Report a vehicle that is blocking your driveway.
997           Report a pothole or cave-in on a street.
998  Give a complaint, compliment, or comment on th...
999  Report a maintenance problem in an apartment, ...

[1000 rows x 6 columns]>

How many rows have we received?

In [7]:
len(data1)

9837

Let's Filter the Data and Increase Limit

We can either edit the query link:

In [28]:
url= 'https://data.cityofnewyork.us/resource/wewp-mm3p.json?$limit=38000000&$where=Agency_Name="Borough President of Queens"'

data = requests.get(url).json()
data=pd.DataFrame(data)
len(data)

#Agency_Name
# Borough President of Queens

#https://data.cityofnewyork.us/resource/wewp-mm3p.json
#data.inquiry_name.value_counts()

#https://data.cityofnewyork.us/resource/wewp-mm3p.json?$query=SELECT%0A%20%20%60unique_id%60%2C%0A%20%20%60date%60%2C%0A%20%20%60time%60%2C%0A%20%20%60date_time%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60inquiry_name%60%2C%0A%20%20%60brief_description%60%2C%0A%20%20%60call_resolution%60%0AWHERE%20%60date%60%20%3E%20%222024-01-01T14%3A15%3A31%22%20%3A%3A%20floating_timestamp

#WHERE%20%60date%60%20%3E%20%222024-01-01T14%3A15%3A31%22%20%3A%3A%20floating_timestamp

#0%60brief_description%60%2C%0A%20%20%60call_resolution%60%0A


0%2C%0A%20%20%60time%60%2C%0A%20%20%60date_time%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60inquiry_name%60%2C%0A%20%20%60brief_description%60%2C%0A%20%20%60call_resolution%60%0AWHERE%20%60date%60%20%3E%20%222024-01-01T14%3A15%3A31%22%20%3A%3A%20floating_timestamp

Street Ownership - Queens        145
Division Information Provided     29
Division Transfer                 17
Division Referral                  7
Staff Information Provided         1
Name: inquiry_name, dtype: int64

In [50]:
#url= 'https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=38000000&$where=agency="NYPD" AND created_date > "2024-03-01" AND descriptor="Blocked Bike Lane"'

url='https://data.cityofnewyork.us/resource/wewp-mm3p.json?$query=SELECT%0A%20%20%60unique_id%60%2C%0A%20%20%60date%60%2C%0A%20%20%60time%60%2C%0A%20%20%60date_time%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60inquiry_name%60%2C%0A%20%20%60brief_description%60%2C%0A%20%20%60call_resolution%60%0AWHERE%20%60date%60%20%3E%20%222024-01-01T14%3A15%3A31%22%20%3A%3A%20floating_timestamp'

url='https://data.cityofnewyork.us/resource/wewp-mm3p.json?$limit=38000000&$where=date>="2024-01-01"'


data = requests.get(url).json()
data=pd.DataFrame(data)
print(len(data))


print(data.head(5))

data.inquiry_name.value_counts() >10


data['Dex']=1
p=['inquiry_name', 'Dex']
c= data[p].groupby(['inquiry_name',]).sum().reset_index() #the reset index is important for AssignedSiteID to separate
c.rename(columns={'Dex':'Count'},inplace= True)
c.query('Count>10')
#Agency_Name
# Borough President of Queens

#https://data.cityofnewyork.us/resource/wewp-mm3p.json

   unique_id                     date         time                date_time  \
0  157455811  2024-01-01T00:00:00.000  12:12:21 AM  2024-01-01T00:12:21.000
1  157455852  2024-01-01T00:00:00.000  12:21:26 AM  2024-01-01T00:21:26.000
2  157456056  2024-01-01T00:00:00.000   1:05:48 AM  2024-01-01T01:05:48.000
3  157456557  2024-01-01T00:00:00.000   3:27:46 AM  2024-01-01T03:27:46.000
4  157456724  2024-01-01T00:00:00.000   4:23:52 AM  2024-01-01T04:23:52.000

          inquiry_name                                  brief_description
0  Fireworks Complaint  Report the sale, use, storage, or transport of...
1  Noise from Neighbor                           Report a noisy neighbor.
2       New Year's Day               Monday, January 1 is New Year's Day.
3  Noise from Neighbor                           Report a noisy neighbor.
4  Noise from Neighbor                           Report a noisy neighbor.

                           inquiry_name  Count
0          3-Day or 10-Day Water Notice    170
1                        3-K Enrollment    901
2                       911 Information    987
4             988 Mental Health Support   8869
6     ACCESS HRA Website and Mobile App    920
...                                 ...    ...
2095                   Youth Employment    697
2096    Youth Employment Working Papers    212
2097      Youth Services and Counseling    373
2099            Zombie Homes Initiative    154
2100                 Zoos and Aquariums    158

[1707 rows x 2 columns]

In [56]:
len(data)
#data.date.value_counts()
data.dtypes

#Convert Date to Datetime!
import datetime
from datetime import datetime

data['DateTime']= pd.to_datetime(data['date_time'])

data['Day']= data['DateTime'].dt.day
print(data['Day'].value_counts())
#Students['BirthMonth']= Students['BirthDateTime'].dt.month
#Students['BirthDay']= Students['BirthDateTime'].dt.dayofyear


df['DateTime']= pd.to_datetime(df['Date']) # Create new column called DateTime
df['Year']= df['DateTime'].dt.year #create year column
df['DayofWeek']=df['DateTime'].dt.dayofweek #create day of the week column where default 0=Monday
df['Weekend'] = df['DayofWeek'].apply(lambda x: 1 if (x>4)  else 0) #Create a weekend category
df['Month'] = df['DateTime'].dt.month # Create Month Category
df['Day'] = df['DateTime'].dt.day #Create Day of the Current month
df['DayYear'] = df['DateTime'].dt.dayofyear  #Create Day of the year (0-365)
df['Day_Max'] = df.iloc[0,-1] #selects uptodate day; NOTE: the data is sorted chronologically

5     106779
1     100651
2      98553
22     95238
8      94782
29     94520
12     91941
26     89911
3      89099
15     88744
16     86311
18     86046
17     85919
25     84943
4      84715
11     84343
10     84256
23     84098
9      83861
24     82315
20     80962
6      78620
19     76789
13     76318
21     76286
28     75972
7      74685
14     72782
30     70392
27     69223
31     49533
Name: Day, dtype: int64

Or we can use SQL:

To group the data with SQL:

In [21]:
query= '''
      SELECT *
      WHERE agency="NYPD"
            AND created_date>"2024-03-01"
            AND descriptor="Blocked Bike Lane"
      '''

url=f'https://data.cityofnewyork.us/resource/erm2-nwe9.json?$query={query}'

data= requests.get(url).json()
data=pd.DataFrame(data)

data.head(5)


# Sample Run

#"2014-10-13T00:00:00.000" 
#https://data.cityofnewyork.us/resource/wewp-mm3p.json?$query=SELECT%0A%20%20%60unique_id%60%2C%0A%20%20%60date%60%2C%0A%20%20%60time%60%2C%0A%20%20%60date_time%60%2C%0A%20%20%60agency%60%2C%0A%20%20%60agency_name%60%2C%0A%20%20%60inquiry_name%60%2C%0A%20%20%60brief_description%60%2C%0A%20%20%60call_resolution%60%0AORDER%20BY%20%60date%60%20DESC%20NULL%20LAST

query1= '''
      SELECT *
      WHERE date> "2024-06-10T00:00:00.000"
          AND inquiry_name="Gas Leak"
      '''

url1=f'https://data.cityofnewyork.us/resource/wewp-mm3p.json?$query={query1}'

data1= requests.get(url1).json()
data1=pd.DataFrame(data1)

data1.head(5)

,unique_id,date,time,date_time,inquiry_name,brief_description
0,159381288,2024-06-11T00:00:00.000,2:52:17 AM,2024-06-11T02:52:17.000,City Agency or Worker Feedback,"Give a complaint, compliment, or comment on th..."
1,159381360,2024-06-11T00:00:00.000,4:07:09 AM,2024-06-11T04:07:09.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
2,159381649,2024-06-11T00:00:00.000,6:46:24 AM,2024-06-11T06:46:24.000,Heat or Hot Water Complaint in a Residential B...,Report a problem with heat or hot water in a r...
3,159381682,2024-06-11T00:00:00.000,6:53:47 AM,2024-06-11T06:53:47.000,Birth Certificate Order,Get a copy of a birth certificate.
4,159381745,2024-06-11T00:00:00.000,7:10:28 AM,2024-06-11T07:10:28.000,Date and Time,Find out today's date and the current time.

In [25]:
query1= '''
      SELECT *
      WHERE inquiry_name="Gas Leak"
          AND date> "2023-06-10T00:00:00.000"
      '''

# date> "2024-06-10T00:00:00.000"

url1=f'https://data.cityofnewyork.us/resource/wewp-mm3p.json?$query={query1}'

data1= requests.get(url1).json()
data1=pd.DataFrame(data1)

data1

,unique_id,date,time,date_time,inquiry_name,brief_description
0,158239314,2024-03-05T00:00:00.000,3:24:20 PM,2024-03-05T15:24:20.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
1,158248749,2024-03-06T00:00:00.000,11:42:11 AM,2024-03-06T11:42:11.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
2,156310471,2023-09-26T00:00:00.000,4:41:00 AM,2023-09-26T04:41:00.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
3,156310656,2023-09-26T00:00:00.000,6:46:46 AM,2023-09-26T06:46:46.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
4,158279708,2024-03-08T00:00:00.000,1:47:11 PM,2024-03-08T13:47:11.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
...,...,...,...,...,...,...
995,156775809,2023-11-02T00:00:00.000,9:19:50 AM,2023-11-02T09:19:50.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
996,156776375,2023-11-02T00:00:00.000,9:32:12 AM,2023-11-02T09:32:12.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
997,156778137,2023-11-02T00:00:00.000,10:52:17 AM,2023-11-02T10:52:17.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
998,156783963,2023-11-02T00:00:00.000,2:56:42 PM,2023-11-02T14:56:42.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...
999,156785057,2023-11-02T00:00:00.000,3:47:02 PM,2023-11-02T15:47:02.000,Gas Leak,Call 911 to report a gas leak or any gas-relat...

In [ ]:
query= '''
      SELECT
        incident_zip,
        COUNT(unique_key) AS count
      WHERE complaint_type = "Illegal Parking"
            AND created_date>"2024-03-01"
            AND borough = "BROOKLYN"
      GROUP BY incident_zip
      '''

url=f'https://data.cityofnewyork.us/resource/erm2-nwe9.json?$query={query}'

data= requests.get(url).json()
data=pd.DataFrame(data)

data

   incident_zip count
0         11201   773
1         11203   126
2         11204   265
3         11205   401
4         11206   127
5         11207   190
6         11208   316
7         11209   415
8         11210   177
9         11211   127
10        11212   130
11        11213   134
12        11214   519
13        11215   471
14        11216   137
15        11217   380
16        11218   303
17        11219   256
18        11220   365
19        11221   146
20        11222   398
21        11223   386
22        11224    88
23        11225   174
24        11226   264
25        11228   202
26        11229   416
27        11230   434
28        11231   345
29        11232   159
30        11233   137
31        11234   269
32        11235   564
33        11236   166
34        11237   160
35        11238   264
36        11239   139
37        11241     3
38        11242     3
39        11249    56
40          NaN     1